# Import The dependencies

In [15]:
import os

import numpy as np
import pandas as pd

from keras.models import Sequential
from keras.layers import LSTM, Dense

# Load the data

In [23]:
path_lstm_data = "../collected_data/data_for_lstm/"

dict_data = dict()

for dir_path in os.listdir(path_lstm_data):
    for file_name in os.listdir(path_lstm_data + f"{dir_path}"):
        dict_data[int(dir_path)] = []
        data_rec = pd.read_csv(path_lstm_data + f"{dir_path}/{file_name}")

        x_data = data_rec[['vertices', 'redexes', 'redex_depths', 'heights', 'widths']].to_numpy()
        y_data = data_rec["steps_time"].to_numpy()
        print(x_data)
        break
    break

[[0. 0. 0. 0. 0.]]


In [27]:
for file_name in os.listdir(path_lstm_data + "4"):
    dict_data[int(dir_path)] = []
    data_rec = pd.read_csv(path_lstm_data + f"4/{file_name}")

    x_data = data_rec[['vertices', 'redexes', 'redex_depths', 'heights', 'widths']].to_numpy()
    y_data = data_rec["steps_time"].to_numpy()
    print(y_data)
    break

[11.56236304 11.39987994 12.53486187 12.00341776]


In [51]:
print(np.random.rand(10).reshape(-1, 1))

[[0.54367805]
 [0.28269965]
 [0.03023526]
 [0.71033683]
 [0.0078841 ]
 [0.37267907]
 [0.53053721]
 [0.92211146]
 [0.08949455]
 [0.40594232]]


In [68]:
# Generate sample data with variable-length sequences
# Replace this with your own data
def generate_sample_data(num_samples, min_timesteps, max_timesteps, num_features):
    np.random.seed(0)
    X, y = [], []
    for _ in range(num_samples):
        timesteps = np.random.randint(min_timesteps, max_timesteps + 1)
        X.append(np.random.rand(timesteps, num_features))
        y.append(np.random.rand(1).reshape(-1, 1))
    return X, y

# Create the LSTM model
def create_lstm_model(max_timesteps, num_features):
    model = Sequential()
    model.add(LSTM(64, input_shape=(None, num_features), activation='relu', return_sequences=False))
    model.add(Dense(1))
    return model

# Compile the model
def compile_model(model):
    model.compile(loss='mean_squared_error', optimizer='adam')

# Train the model
def train_model(model, X, y, epochs=10, batch_size=32):
    model.fit(X, y, epochs=epochs, batch_size=batch_size)

In [69]:
# Example usage
num_samples = 10
min_timesteps = 10
max_timesteps = 10
num_features = 5

X, y = generate_sample_data(num_samples, min_timesteps, max_timesteps, num_features)

max_timesteps = max([seq.shape[0] for seq in X])  # Update max_timesteps based on the actual maximum length
model = create_lstm_model(max_timesteps, num_features)
compile_model(model)
train_model(model, X, y)

# Once the model is trained, you can use it for predictions
# Replace `new_data` with your new input data for prediction
new_data = np.random.rand(1, max_timesteps, num_features)
predictions = model.predict(new_data)

print("Output from each LSTM step:")
for timestep_output in predictions[0]:
    print(timestep_output[0])

ValueError: Data cardinality is ambiguous:
  x sizes: 10, 10, 10, 10, 10, 10, 10, 10, 10, 10
  y sizes: 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
Make sure all arrays contain the same number of samples.

In [65]:
model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_14 (LSTM)              (None, None, 64)          17920     
                                                                 
 dense_14 (Dense)            (None, None, 1)           65        
                                                                 
Total params: 17985 (70.25 KB)
Trainable params: 17985 (70.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [44]:
for row in X:
    print(row, "\n")

[[0.84426575 0.85794562 0.84725174 0.6235637  0.38438171]
 [0.29753461 0.05671298 0.27265629 0.47766512 0.81216873]
 [0.47997717 0.3927848  0.83607876 0.33739616 0.64817187]
 [0.36824154 0.95715516 0.14035078 0.87008726 0.47360805]
 [0.80091075 0.52047748 0.67887953 0.72063265 0.58201979]
 [0.53737323 0.75861562 0.10590761 0.47360042 0.18633234]] 

[[0.94374808 0.6818203  0.3595079  0.43703195 0.6976312 ]
 [0.06022547 0.66676672 0.67063787 0.21038256 0.1289263 ]] 

[[0.03842543 0.63427406 0.95894927 0.65279032 0.63505887]
 [0.99529957 0.58185033 0.41436859 0.4746975  0.6235101 ]
 [0.33800761 0.67475232 0.31720174 0.77834548 0.94957105]
 [0.66252687 0.01357164 0.6228461  0.67365963 0.971945  ]
 [0.87819347 0.50962438 0.05571469 0.45115921 0.01998767]
 [0.44171092 0.97958673 0.35944446 0.48089353 0.68866118]
 [0.88047589 0.91823547 0.21682214 0.56518887 0.86510256]
 [0.50896896 0.91672295 0.92115761 0.08311249 0.27771856]
 [0.0093567  0.84234208 0.64717414 0.84138612 0.26473016]
 [0.3978

In [42]:
y

[array([0.73691818, 0.21655035, 0.13521817, 0.32414101, 0.14967487,
        0.22232139]),
 array([0.31542835, 0.36371077]),
 array([0.56961841, 0.70373728, 0.28847644, 0.43328806, 0.75610669,
        0.39609828, 0.89603839, 0.63892108, 0.89155444, 0.68005557]),
 array([0.8811032]),
 array([0.05058812, 0.36549611, 0.01662797, 0.23074234, 0.7649117 ,
        0.94412352, 0.74999925, 0.33940382, 0.48954894]),
 array([0.37775184, 0.17960368, 0.02467873, 0.06724963, 0.67939277,
        0.45369684]),
 array([0.20915703, 0.28691504, 0.67726331, 0.06303829, 0.55564924,
        0.00924007, 0.8330381 , 0.98432943, 0.70349478, 0.1816312 ]),
 array([0.72704426, 0.27032791, 0.1314828 , 0.05537432, 0.30159863,
        0.26211815, 0.45614057, 0.68328134, 0.69562545, 0.28351885]),
 array([0.47322067, 0.58019711, 0.71624417, 0.02706898, 0.73139734,
        0.76696351, 0.00976644, 0.30828617]),
 array([0.0324653 , 0.58015172, 0.77108905, 0.37622657, 0.49102474,
        0.98163968, 0.24465141])]