# Import The dependencies

In [28]:
import os

import numpy as np
import pandas as pd
import random

from keras.models import Sequential
from keras.layers import LSTM, Dense

# Load the data

In [22]:
path_lstm_data = "../collected_data/data_for_lstm/"

dict_data = dict()

for dir_path in os.listdir(path_lstm_data):
    y_data_samples = []
    x_data_samples = []
    for file_name in os.listdir(path_lstm_data + f"{dir_path}"):
        dict_data[int(dir_path)] = []
        data_rec = pd.read_csv(path_lstm_data + f"{dir_path}/{file_name}")

        x_data = data_rec[['vertices', 'redexes', 'redex_depths', 'heights', 'widths']].to_numpy()
        y_data = data_rec["steps_time"].to_numpy()
        x_data_samples.append(x_data)
        y_data_samples.append([y_data[-1]])
    dict_data[int(dir_path)] = (np.array(x_data_samples), np.array(y_data_samples))

In [24]:
print(dict_data[1])

(array([[[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]]]), array([[10.57328934],
       [11.1813751 ],
       [11.95320415],
       [11.1595878 ],
       [12.33206192],
       [11.89018998],
       [10.18323825],
       [11.21044104],
       [10.69010231],
       [10.73934884],
       [10.79359857],
       [12.38369568],
       [12.36640844],
       [11.5875226 ],
       [12.1871395

# Define the LSTM model

In [25]:
def create_lstm_model(input_shape=(None, 5)):
    model_ = Sequential()
    model_.add(LSTM(64, input_shape=input_shape, activation='relu'))
    model_.add(Dense(1))

    model_.compile(loss='mean_squared_error', optimizer='adam')
    return model_


def train_model(model_, x_train_data, y_train_data, epochs=1, batch_size=32):
    model_.fit(x_train_data, y_train_data, epochs=epochs, batch_size=batch_size)

In [26]:
model = create_lstm_model()

In [29]:
count_epochs = 25
for epoch in range(count_epochs):
    print(f"{epoch}:\n")

    rand_keys = list(dict_data.keys())
    random.shuffle(rand_keys)
    for key_ in rand_keys:
        xtd, ytd = dict_data[key_]
        train_model(model, xtd, ytd)

0:

Epoch 1/10
2/2 [==============================] - 2s 70ms/step - loss: 115.4918
Epoch 2/10
2/2 [==============================] - 0s 60ms/step - loss: 114.6881
Epoch 3/10
2/2 [==============================] - 0s 62ms/step - loss: 113.1479
Epoch 4/10
2/2 [==============================] - 0s 67ms/step - loss: 112.2068
Epoch 5/10
2/2 [==============================] - 0s 63ms/step - loss: 110.3030
Epoch 6/10
2/2 [==============================] - 0s 80ms/step - loss: 106.8860
Epoch 7/10
2/2 [==============================] - 0s 63ms/step - loss: 105.2210
Epoch 8/10
2/2 [==============================] - 0s 60ms/step - loss: 104.5720
Epoch 9/10
2/2 [==============================] - 0s 60ms/step - loss: 102.2865
Epoch 10/10
2/2 [==============================] - 0s 61ms/step - loss: 97.9723
Epoch 1/10
1/1 [==============================] - 1s 882ms/step - loss: 127.6958
Epoch 2/10
1/1 [==============================] - 0s 22ms/step - loss: 127.6358
Epoch 3/10
1/1 [===================

# Test the model

# Save the model

# Some tests

In [7]:
# Generate sample data
# Replace this with your own data
def generate_sample_data(num_timesteps=5, num_features=5):
    np.random.seed(0)
    num_samples = 1000
    X = np.random.rand(num_samples, num_timesteps, num_features)
    y = np.random.rand(num_samples, 1)
    return X, y


# Create the LSTM model
def create_lstm_model(input_shape):
    model = Sequential()
    model.add(LSTM(64, input_shape=input_shape, activation='relu'))
    model.add(Dense(1))
    return model


# Compile the model
def compile_model(model):
    model.compile(loss='mean_squared_error', optimizer='adam')


# Train the model
def train_model(model, X, y, epochs=10, batch_size=32):
    model.fit(X, y, epochs=epochs, batch_size=batch_size)

In [8]:
# Example usage
X, y = generate_sample_data()
num_timesteps, num_features = X.shape[1], X.shape[2]
model = create_lstm_model(input_shape=(None, num_features))
compile_model(model)
train_model(model, X, y)

# Once the model is trained, you can use it for predictions
# Replace `new_data` with your new input data for prediction
new_data = np.random.rand(5, num_timesteps, num_features)
prediction = model.predict(new_data)
print("Predicted time spent on step:", prediction[0][0])

Epoch 1/10
32/32 [==============================] - 5s 64ms/step - loss: 0.1727
Epoch 2/10
32/32 [==============================] - 2s 61ms/step - loss: 0.0837
Epoch 3/10
32/32 [==============================] - 2s 64ms/step - loss: 0.0840
Epoch 4/10
32/32 [==============================] - 2s 64ms/step - loss: 0.0807
Epoch 5/10
32/32 [==============================] - 2s 55ms/step - loss: 0.0837
Epoch 6/10
32/32 [==============================] - 2s 51ms/step - loss: 0.0806
Epoch 7/10
32/32 [==============================] - 2s 56ms/step - loss: 0.0821
Epoch 8/10
32/32 [==============================] - 2s 50ms/step - loss: 0.0842
Epoch 9/10
32/32 [==============================] - 2s 53ms/step - loss: 0.0821
Epoch 10/10
32/32 [==============================] - 2s 48ms/step - loss: 0.0834
Predicted time spent on step: 0.5284022


In [13]:
X, y = generate_sample_data(num_timesteps=10)
train_model(model, X, y)

Epoch 1/10
32/32 [==============================] - 4s 82ms/step - loss: 0.0885
Epoch 2/10
32/32 [==============================] - 3s 81ms/step - loss: 0.0845
Epoch 3/10
32/32 [==============================] - 2s 73ms/step - loss: 0.0859
Epoch 4/10
32/32 [==============================] - 2s 74ms/step - loss: 0.0841
Epoch 5/10
32/32 [==============================] - 2s 72ms/step - loss: 0.0847
Epoch 6/10
32/32 [==============================] - 2s 69ms/step - loss: 0.0839
Epoch 7/10
32/32 [==============================] - 2s 76ms/step - loss: 0.0838
Epoch 8/10
32/32 [==============================] - 2s 70ms/step - loss: 0.0834
Epoch 9/10
32/32 [==============================] - 3s 80ms/step - loss: 0.0836
Epoch 10/10
32/32 [==============================] - 3s 84ms/step - loss: 0.0844


In [14]:
X, y = generate_sample_data(num_timesteps=100)
train_model(model, X, y)

Epoch 1/10
32/32 [==============================] - 22s 660ms/step - loss: 0.0857
Epoch 2/10
32/32 [==============================] - 22s 702ms/step - loss: 0.0853
Epoch 3/10
32/32 [==============================] - 21s 663ms/step - loss: 0.0859
Epoch 4/10
32/32 [==============================] - 21s 667ms/step - loss: 0.0849
Epoch 5/10
32/32 [==============================] - 19s 594ms/step - loss: 0.0844
Epoch 6/10
32/32 [==============================] - 23s 709ms/step - loss: 0.0845
Epoch 7/10
32/32 [==============================] - 24s 762ms/step - loss: 0.0841
Epoch 8/10
32/32 [==============================] - 24s 751ms/step - loss: 0.0841
Epoch 9/10
32/32 [==============================] - 24s 739ms/step - loss: 0.0836
Epoch 10/10
32/32 [==============================] - 19s 583ms/step - loss: 0.0835


In [ ]:
model.summary()

In [9]:
for row in X:
    print(row, "\n")

[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]] 

[[0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]
 [0.6176355  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672]
 [0.67063787 0.21038256 0.1289263  0.31542835 0.36371077]] 

[[0.57019677 0.43860151 0.98837384 0.10204481 0.20887676]
 [0.16130952 0.65310833 0.2532916  0.46631077 0.24442559]
 [0.15896958 0.11037514 0.65632959 0.13818295 0.19658236]
 [0.36872517 0.82099323 0.09710128 0.83794491 0.09609841]
 [0.97645947 0.4686512  0.97676109 0.60484552 0.73926358]] 

[[0.03918779 0.28280696 0.12019656 0.2961402  0.11872772]
 [0.31798318 0.41426299 0.0641475  0.69247212 0.56660145]
 [0.2

In [10]:
print(y)

[[0.8812033 ]
 [0.53122103]
 [0.8680575 ]
 [0.77755907]
 [0.96932112]
 [0.92571412]
 [0.16927561]
 [0.57996402]
 [0.02856338]
 [0.68828411]
 [0.54150551]
 [0.14278145]
 [0.66640611]
 [0.36708941]
 [0.09459162]
 [0.00299151]
 [0.60631975]
 [0.79011012]
 [0.47399445]
 [0.36391856]
 [0.75603037]
 [0.0063267 ]
 [0.80624946]
 [0.14631303]
 [0.2934198 ]
 [0.61383733]
 [0.8059898 ]
 [0.14708033]
 [0.66029159]
 [0.40847581]
 [0.25638414]
 [0.39374154]
 [0.38463804]
 [0.83570583]
 [0.53699062]
 [0.84165466]
 [0.16601442]
 [0.83759583]
 [0.3109018 ]
 [0.71662891]
 [0.49894272]
 [0.59874476]
 [0.64255778]
 [0.64013713]
 [0.93336891]
 [0.68057536]
 [0.57611589]
 [0.27045168]
 [0.83392349]
 [0.2913378 ]
 [0.46407066]
 [0.38620976]
 [0.51723503]
 [0.96851869]
 [0.04338821]
 [0.52355474]
 [0.20492708]
 [0.12709019]
 [0.50011878]
 [0.53641198]
 [0.69838596]
 [0.28335574]
 [0.01419542]
 [0.42349172]
 [0.29702545]
 [0.94713859]
 [0.44958176]
 [0.80243926]
 [0.971418  ]
 [0.07014468]
 [0.66927981]
 [0.82